### ISSUE TITLE
there is no crypto.pseudoRandomBytes api

### ISSUE THREAD

**Issue by anlexN** [suryagh/tsscmp#17]
![image](https://user-images.githubusercontent.com/8686739/91322316-2cec3180-e7f2-11ea-9fa2-92ab77321bdb.png)
in the all LTS and current, node have supported crypto.timingSafeEqual api, can we give up this repo?

**Comment by suryagh** [comment]
Yes, this is only required for libraries/frameworks that also need to support older versions of node. `pseudoRandomBytes ` is an alias for `randomBytes` in newer versions of node.  However, `pseudoRandomBytes` is a separate implementation in older versions of node where it wouldn't error on insufficient entropy. Since, `> v10` node pool blocks on insufficient entropy and would not result in error, hence it is redirected to `randomBytes` these days, which is not the case with `< v10`
